name: glypruneabc_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy==1.26.4
    - pandas==2.2.1
    - matplotlib==3.8.4
    - pyabc==0.12.13
    - networkx==3.3
    - pyvis==0.3.2
    - glycowork==1.2.0
    - natsort==8.4.0
    - scipy==1.12.0
